#!/usr/bin/env python3
"""Writes gno/p/worldmap/countries.gno, the shapes and projection the map draws.

    ./scripts/worldmap.py

Reads Natural Earth's 1:110m countries from the world-atlas package and
projects them with Robinson's table, from 84N down to 58S, since the Arctic
sea and Antarctica only take room. Antarctica is left out. The file carries
the table too, so the package places each dot with the same projection.

A shape crossing the date line is drawn twice, once past each edge, and the
map clips the land to the ocean's outline, so no line runs across the map.
"""

import json
import math
import os
import urllib.request

SOURCE = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
ANTARCTICA = "010"
OUT = os.path.join(os.path.dirname(__file__), "..", "gno", "p", "worldmap", "countries.gno")

UNIT = 5  # path units per degree of longitude on the equator
TOP, BOTTOM = 84, -58

# Robinson's table, every 5 degrees of latitude from the equator: how much a
# parallel shrinks, and how far from the equator it sits.
ROBINSON_X = [1.0000, 0.9986, 0.9954, 0.9900, 0.9822, 0.9730, 0.9600, 0.9427, 0.9216, 0.8962,
              0.8679, 0.8350, 0.7986, 0.7597, 0.7186, 0.6732, 0.6213, 0.5722, 0.5322]
ROBINSON_Y = [0.0000, 0.0620, 0.1240, 0.1860, 0.2480, 0.3100, 0.3720, 0.4340, 0.4958, 0.5571,
              0.6176, 0.6769, 0.7346, 0.7903, 0.8435, 0.8936, 0.9394, 0.9761, 1.0000]
Y_SCALE = round(1.3523 / 0.8487 * 180 / math.pi * UNIT * 1000)  # path units per Y, x1000


def interp(table, lat):
    a = min(abs(lat), 89.999) / 5
    i = int(a)
    return table[i] + (table[i + 1] - table[i]) * (a - i)


def project(lon, lat):
    """Returns the Robinson position of a point, x from the map's west edge
    and y from the equator, north positive."""
    x = interp(ROBINSON_X, lat) * lon * UNIT + 180 * UNIT
    y = math.copysign(interp(ROBINSON_Y, lat), lat) * Y_SCALE / 1000
    return x, y


ORIGIN_Y = round(project(0, TOP)[1])
WIDTH = 360 * UNIT
HEIGHT = ORIGIN_Y - round(project(0, BOTTOM)[1])


def rings(topo):
    """Yields every polygon ring of every country as (lon, lat) points."""
    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)

    def ring(ids):
        pts = []
        for i in ids:
            a = arcs[i] if i >= 0 else arcs[~i][::-1]
            pts.extend(a if not pts else a[1:])
        return pts

    for geom in topo["objects"]["countries"]["geometries"]:
        if geom.get("id") == ANTARCTICA or geom["type"] not in ("Polygon", "MultiPolygon"):
            continue
        polys = geom["arcs"] if geom["type"] == "MultiPolygon" else [geom["arcs"]]
        for poly in polys:
            for r in poly:
                yield ring(r)


def unwrapped(rs):
    """Yields each ring with continuous longitudes, plus a copy shifted by
    360 degrees for a ring that runs past either edge."""
    for r in rs:
        out = [r[0]]
        for lon, lat in r[1:]:
            prev = out[-1][0]
            while lon - prev > 180:
                lon -= 360
            while lon - prev < -180:
                lon += 360
            out.append((lon, lat))
        yield out
        if max(x for x, _ in out) > 180:
            yield [(x - 360, y) for x, y in out]
        if min(x for x, _ in out) < -180:
            yield [(x + 360, y) for x, y in out]


def path(rs):
    parts = []
    for r in rs:
        pts = []
        for lon, lat in r:
            x, y = project(lon, lat)
            pts.append((round(x), ORIGIN_Y - round(y)))
        px, py = pts[0]
        moves = []
        for x, y in pts[1:]:
            if (x, y) != (px, py):
                moves.append((x - px, y - py))
                px, py = x, y
        if len(moves) < 2:
            continue
        d = "l" + " ".join("%d %d" % m for m in moves)
        parts.append("M%d %d%sz" % (pts[0][0], pts[0][1], d.replace(" -", "-")))
    return "".join(parts)


def main():
    with urllib.request.urlopen(SOURCE) as resp:
        topo = json.load(resp)
    edge = [(180, lat) for lat in range(TOP, BOTTOM - 1, -1)] + \
        [(-180, lat) for lat in range(BOTTOM, TOP + 1)]
    table = lambda t: ", ".join(str(round(v * 10000)) for v in t)
    with open(OUT, "w") as f:
        f.write("// Code generated by scripts/worldmap.py. DO NOT EDIT.\n\n")
        f.write("package worldmap\n\n")
        f.write("// The map in path units, %d per degree of longitude on the equator.\n" % UNIT)
        f.write("const (\n")
        f.write("\tunit    = %d\n" % UNIT)
        f.write("\twidth   = %d\n" % WIDTH)
        f.write("\theight  = %d\n" % HEIGHT)
        f.write("\toriginY = %d // the equator, from the top edge at %dN\n" % (ORIGIN_Y, TOP))
        f.write("\tminLat  = %d // hundredths of a degree\n" % (BOTTOM * 100))
        f.write("\tmaxLat  = %d\n" % (TOP * 100))
        f.write("\t// yScale is path units per unit of robinsonY, times 1000.\n")
        f.write("\tyScale = %d\n" % Y_SCALE)
        f.write(")\n\n")
        f.write("// robinsonX and robinsonY are Robinson's table every 5 degrees from the\n")
        f.write("// equator, times 10000: how much a parallel shrinks, and its height.\n")
        f.write("var (\n")
        f.write("\trobinsonX = [...]int{%s}\n" % table(ROBINSON_X))
        f.write("\trobinsonY = [...]int{%s}\n" % table(ROBINSON_Y))
        f.write(")\n\n")
        f.write("// oceanPath is the map's outline, the curved edge of the world.\n")
        f.write('const oceanPath = "%s"\n\n' % path([edge]))
        f.write("// countriesPath draws every country but Antarctica.\n")
        f.write('const countriesPath = "%s"\n' % path(unwrapped(rings(topo))))


if __name__ == "__main__":
    main()
